version: "3.6"
services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres
volumes:
  db_data:
